name: Docker Image CI

on:
  push:
    branches: [ "staging", "release", "develop" ]
  pull_request:
    branches: [ "staging", "release", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login into Docker
      env:
        DOCKER_URL: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASS" | docker login $DOCKER_URL -u "$DOCKER_USER" --password-stdin
    
    - name: Build the Docker image
      run: docker build --file web/Dockerfile --tag wband/web:${{ github.ref_name }}
      
    - name: Tag the Docker image
      run: docker tag --file web/Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/wband/web:${{ github.ref_name }}

    - name: Push the Docker image
      run: docker push --tag ${{ secrets.DOCKER_REGISTRY }}/wband/web:${{ github.ref_name }}
      
